import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home - Joof.io</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      {/* <Header /> */}

      <div className="bg-slate-300">
        <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4 ">
          <h1 className="text-5xl font-semibold leading-tight tracking-tight">Buy and Sell digital goods with 0% fees</h1>
        </main>
        <img 
            src="https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg"
            width=""
          />
      </div>
    </>
  );
};

export default Home;
